# Build only pushed (merged) master or any pull request. This avoids the
# pull request to be build twice.
branches:
  only:
    - master

language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - windows
  - osx

git:
  depth: 1
  quiet: true

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH=$PATH:/home/travis/.cargo/bin
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --version
  - rustup --version
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then cargo fmt --all -- --check; fi
  - cargo clippy -- -D clippy::all
  - cargo build
  - cargo test --all-features --no-default-features -- --nocapture --test-threads 1
  - cargo test --features cursor --no-default-features --lib -- --nocapture --test-threads 1
  - cargo test --features style --no-default-features --lib -- --nocapture --test-threads 1
  - cargo test --features terminal --no-default-features --lib -- --nocapture --test-threads 1
  - cargo test --features screen --no-default-features --lib -- --nocapture --test-threads 1
  - cargo test --features event --no-default-features --lib -- --nocapture --test-threads 1
  - cargo test --features event-stream --no-default-features --lib -- --nocapture --test-threads 1
