# Set up the Rust toolchain.
language: rust
rust:
  - stable

before_script:
  - export PATH=$PATH:/home/travis/.cargo/bin
  - rustup component add rustfmt-preview

os:
  - linux
  - osx
  - windows

script:
  - cargo build
  - cargo fmt -- --check
  - cargo test -- --nocapture --test-threads 1
