# Set up the Rust toolchain.
language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - windows
  - osx

git:
  depth: 1
  quiet: true

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH=$PATH:/home/travis/.cargo/bin
  - rustup component add rustfmt

script:
  - cargo fmt --version
  - rustup --version
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then cargo fmt --all -- --check; fi
  - cargo build
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo test --all -- --nocapture --test-threads 1; else cargo test --all --exclude crossterm_winapi -- --nocapture --test-threads 1; fi
  - |
    pushd examples/program_examples
    for d in */ ; do
      pushd "$d"
      cargo build
      if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then cargo fmt --all -- --check; fi
      popd
    done
    popd
