[package]
name = "crossterm"
version = "0.6.0"
authors = ["T. Post"]
description = "An crossplatform terminal library for manipulating terminals."
repository = "https://github.com/TimonPost/crossterm"
documentation = "https://docs.rs/crossterm/"
license = "MIT"
keywords = ["console", "color", "cursor", "input", "terminal"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"

[target.'cfg(windows)'.dependencies]
winapi = { version =  "0.3.5", features = ["winbase","winuser","consoleapi","processenv","wincon", "handleapi","errhandlingapi"] }
crossterm_winapi = "0.1.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.43"
termios = "0.3.0"

[lib]
name = "crossterm"
path = "src/lib.rs"

[[example]]
name = "examples"
path = "examples/examples.rs"

[[example]]
name = "logging"
path = "examples/program_examples/logging.rs"

[[example]]
name = "command_bar"
path = "examples/program_examples/command_bar.rs"
