[package]
name = "crossterm"
version = "0.13.0"
authors = ["T. Post"]
description = "An crossplatform terminal library for manipulating terminals."
repository = "https://github.com/crossterm-rs/crossterm"
documentation = "https://docs.rs/crossterm/"
license = "MIT"
keywords = ["console", "color", "cursor", "input", "terminal"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"
edition = "2018"
categories = ["Command-line interface", "Command line utilities"]

[features]
default = ["cursor", "style", "terminal", "screen", "input"]
cursor = ["lazy_static", "input", "winapi/wincon", "winapi/winnt", "winapi/minwindef"]
style = ["lazy_static", "winapi/wincon"]
terminal = ["cursor"]
screen = ["lazy_static", "winapi/wincon", "winapi/minwindef"]
input = ["mio", "lazy_static", "screen", "winapi/winnt", "winapi/winuser"]

[dependencies]
lazy_static = { version = "1.4", optional = true }
serde = { version = "1.0.0", features = ["derive"], optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
crossterm_winapi = "0.3.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.51"
mio = { version = "0.6.19", optional = true }

[lib]
name = "crossterm"
path = "src/lib.rs"
