name: Crossterm Test

on:
  # Build master branch only
  push:
    branches:
      - master
  # Build pull requests targeting master branch only
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{matrix.rust}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        rust: [stable, nightly]
        # Allow failures on nightly, it's just informative
        include:
          - rust: stable
            can-fail: false
          - rust: nightly
            can-fail: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt,clippy
    - name: Toolchain Information
      run: |
        rustc --version
        rustfmt --version
        rustup --version
        cargo --version
    - name: Check Formatting
      if: matrix.rust == 'stable'
      run: cargo fmt --all -- --check
      continue-on-error: ${{ matrix.can-fail }}
    - name: Clippy
      run: cargo clippy -- -D clippy::all
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test Build
      run: cargo build
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test all features
      run: cargo test --all-features --no-default-features -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test cursor feature
      run: cargo test --features cursor --no-default-features --lib -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test style feature
      run: cargo test --features style --no-default-features --lib -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test terminal feature
      run: cargo test --features terminal --no-default-features --lib -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test screen feature
      run: cargo test --features screen --no-default-features --lib -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test event feature
      run: cargo test --features event --no-default-features --lib -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test async-event feature
      run: cargo test --features event-stream --no-default-features --lib -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test Packaging
      if: matrix.rust == 'stable'
      run: cargo package
      continue-on-error: ${{ matrix.can-fail }}
